In [2]:
import pandas as pd

pd.set_option('display.max_columns',None)

In [3]:
df_c = pd.read_csv('../Datos.Originales/bank-additional.csv')
df_e = pd.read_excel('../Datos.Originales/customer-details.xlsx')

In [4]:
df_e.sample(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
9479,9479,6520,1,2,2012-04-05,12,d08cdc2c-4731-41f5-b61a-b718a3445c70
11803,11803,178511,1,2,2012-07-07,11,cbc013a6-99ff-4601-859f-efc64d6e5d30
15393,15393,128105,0,2,2012-01-07,8,0cd6ff83-b362-4f5d-a90f-d528de31b6e3
13107,13107,15578,0,1,2012-07-13,3,ac17373a-dc07-4bf6-8b05-9978927c91f9
14825,14825,162537,0,2,2012-06-07,13,fcf4a355-2850-40eb-9c58-ea17618d4905

In [5]:
df_c.sample(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
25802,25924,41.0,admin.,MARRIED,university.degree,0.0,1.0,1.0,telephone,385,1,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,12","5195,8",no,15-febrero-2019,37.765,-78.788,2e649eaf-316d-431a-bd78-b4660298808d
1939,2036,32.0,admin.,SINGLE,university.degree,0.0,0.0,0.0,telephone,409,2,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,16-noviembre-2016,43.506,-86.583,5b13044c-59e2-415c-ae65-4a3af9048855
14965,15062,26.0,technician,SINGLE,high.school,0.0,0.0,0.0,cellular,224,2,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,958","5228,1",no,27-diciembre-2019,30.925,-113.656,78b93d97-d426-4195-98ba-cdaa0deb6f50
31358,31502,41.0,blue-collar,MARRIED,basic.4y,0.0,1.0,0.0,cellular,187,8,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,334","5099,1",no,3-enero-2017,35.031,-108.612,1d2bb81b-d982-4f8a-b3cd-5a964a49c16e
5705,5802,45.0,admin.,SINGLE,NaN,NaN,0.0,0.0,telephone,87,3,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,31-marzo-2018,44.026,-116.599,1c54f8ea-b98a-4a12-90cf-6a83d6aa4e6c

In [6]:
df_c.columns

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='object')

In [7]:
df_e.columns

Index(['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer',
       'NumWebVisitsMonth', 'ID'],
      dtype='object')

comprobamos si todos los elementos de df_e estan en df_c

In [8]:
ids_c = set(df_c['id_'])
ids_e = set(df_e['ID'])

In [17]:
ids_no_en_e = ids_c - ids_e
ids_no_en_e_series = pd.Series(list(ids_no_en_e))
Num_ids_no_en_e = len(ids_no_en_e_series)
Num_ids_no_en_e

22982

In [23]:
df_2012 = pd.read_excel('../Datos.Originales/customer-details.xlsx', sheet_name ='2012')
df_2013 = pd.read_excel('../Datos.Originales/customer-details.xlsx', sheet_name ='2013')
df_2014 = pd.read_excel('../Datos.Originales/customer-details.xlsx', sheet_name ='2014')

In [24]:
df_años_unificado = pd.concat([df_2012,df_2013,df_2014], ignore_index=True)

In [25]:
ids_c = set(df_c['id_'])
ids_u = set(df_años_unificado['ID'])

In [26]:
ids_no_en_u = ids_c - ids_u
ids_no_en_u_series = pd.Series(list(ids_no_en_u))
Num_ids_no_en_u = len(ids_no_en_u_series)
Num_ids_no_en_u

0

In [27]:
ids_no_en_c = ids_u - ids_c
ids_no_en_c_series = pd.Series(list(ids_no_en_c))
Num_ids_no_en_c = len(ids_no_en_c_series)
Num_ids_no_en_c

170

In [ ]:

df_años_unificado.sample(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
2235,2235,154340,1,2,2012-10-02,11,058994d7-ff88-4fd6-8384-82b909742e2e
18497,18497,118461,2,0,2012-01-19,10,3d1dfd95-0854-4cde-9651-a9ab1b503b47
20841,726,157632,0,1,2013-08-19,20,47bd59b4-2868-49e2-8742-7a48dfdbfcc0
34657,5577,91766,2,0,2014-10-09,27,52e594ba-4b4c-4ce1-aa1c-3861db3f38a9
27298,7183,62966,1,0,2013-05-22,10,1ee10b1c-bdd4-47f7-bb4f-247b93861f85

In [39]:
# Contar duplicados en df_c['id_']
num_duplicados_df_c = df_c['id_'].duplicated(keep=False).sum()
print(f"Número de duplicados en df_c['id']: {num_duplicados_df_c}")

# Contar duplicados en df_años_unificado['ID']
num_duplicados_df_años_unificado = df_años_unificado['ID'].duplicated(keep=False).sum()
print(f"Número de duplicados en df_años_unificado['ID']: {num_duplicados_df_años_unificado}")

Número de duplicados en df_c['id']: 0
Número de duplicados en df_años_unificado['ID']: 0

No hay duplicados en ninguno de los dos ID's asi que procedemos a la union de dos df

In [34]:
df_unidos =pd.merge(df_c,df_años_unificado, left_on='id_', right_on='ID', how='left')

In [35]:
df_unidos.sample(5)

,Unnamed: 0_x,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,Unnamed: 0_y,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
8527,8624,32.0,services,MARRIED,high.school,NaN,1.0,0.0,telephone,833,2,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,864","5228,1",no,4-julio-2015,41.104,-73.540,555f2bf6-09ad-4e02-8b1b-c5ab86848578,8624,22244,2,1,2012-03-10,25,555f2bf6-09ad-4e02-8b1b-c5ab86848578
5201,5298,41.0,blue-collar,DIVORCED,basic.6y,0.0,0.0,0.0,telephone,253,2,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,8-marzo-2018,43.930,-115.466,b6dcb38d-9dc9-451e-b19d-d2b4be81dad3,5298,150481,0,2,2012-10-28,7,b6dcb38d-9dc9-451e-b19d-d2b4be81dad3
34928,35072,33.0,blue-collar,MARRIED,basic.9y,NaN,1.0,0.0,cellular,730,5,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,25","5099,1",yes,18-diciembre-2017,42.211,-102.054,9de1a6f2-ee23-4e5f-ba92-2f595a3a4c1e,5992,93167,2,1,2014-12-16,1,9de1a6f2-ee23-4e5f-ba92-2f595a3a4c1e
37120,37287,33.0,admin.,MARRIED,high.school,0.0,1.0,0.0,cellular,252,1,6,1,SUCCESS,-2.9,"92,201","-31,4","0,884","5076,2",yes,5-agosto-2019,25.906,-113.901,c8668934-4c77-40b0-963c-8c1d3dd24f8e,8207,37370,1,1,2014-02-09,18,c8668934-4c77-40b0-963c-8c1d3dd24f8e
25334,25456,48.0,blue-collar,SINGLE,basic.9y,0.0,1.0,0.0,cellular,43,1,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,12","5195,8",no,29-enero-2017,30.890,-120.487,ed630aaa-295a-4141-988c-9bdee598bd05,5341,162043,2,0,2013-01-01,21,ed630aaa-295a-4141-988c-9bdee598bd05

guardamos el nuevo data frame unificado a un nuevo csv

In [41]:
df_unidos.to_csv('../Datos/df_data_unificada.csv', index=False)