# LIMPIEZA

In [1]:
#Tratamiento de datos
import pandas as pd

pd.set_option('display.max_columns',None)

#Exploracion de archivos
import sys
sys.path.append('../')

#funciones personalizadas
from SRC import sp_eda as se
from SRC import sp_limpieza as sl

In [2]:
df_u = pd.read_csv('../Datos/df_data_unificada.csv')

AJUSTE NOMBRE COLUMNAS

In [3]:

#Cambion de nombre de columnas (espacios y puntos por "_")
df_u.columns = df_u.columns.str.replace(' ', '_')
df_u.columns = df_u.columns.str.replace('.', '_')
df_u.columns = df_u.columns.str.lower()

In [4]:
df_u.columns

Index(['unnamed:_0_x', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y', 'date', 'latitude',
       'longitude', 'id_', 'unnamed:_0_y', 'income', 'kidhome', 'teenhome',
       'dt_customer', 'numwebvisitsmonth', 'id'],
      dtype='object')

### LIMPIEZA

ELIMINACION DE COLUMNAS

In [5]:
df_u = df_u.drop(columns=['unnamed:_0_x', 'unnamed:_0_y', 'id_'])

AGE

In [6]:
#Conversion de float a Integer
df_u['age'] = df_u['age'].astype('Int64')

N.EMPLEADOS

In [7]:
#cambio "," por "." y conversion de Object a integer
df_u['nr_employed'] = df_u['nr_employed'].str.replace(',', '.').str.strip()
df_u['nr_employed'] = df_u['nr_employed'].astype(float).astype(int)

In [8]:
df_u['job'].unique()

array(['housemaid', 'services', 'admin.', 'blue-collar', 'technician',
       'retired', 'management', 'unemployed', 'self-employed', nan,
       'entrepreneur', 'student'], dtype=object)

JOB

In [9]:
# Cambio "-" por "_" y eliminacion de "." al final de admin
df_u['job'] = df_u['job'].str.replace('-', '_').str.strip('.')  # quitar espacios

FECHAS

In [10]:
df_u.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,latitude,longitude,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id
21183,34,admin,SINGLE,university.degree,NaN,0.0,1.0,cellular,103,3,999,0,NONEXISTENT,1.4,"93,444","-36,1","4,963",5228,no,27-noviembre-2017,45.838,-79.415,152321,1,1,2013-12-22,29,eb8282e4-1577-43fb-8629-3330a8df3ef8
35719,37,technician,MARRIED,university.degree,0.0,1.0,1.0,cellular,239,1,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,259",5099,no,28-febrero-2019,46.521,-73.689,115689,2,1,2014-06-20,12,72c99407-b1fd-4ca2-a8db-2722135c57ac
30667,33,admin,SINGLE,high.school,0.0,0.0,0.0,cellular,399,1,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,344",5099,no,16-julio-2017,24.983,-69.108,105326,2,0,2014-10-12,19,c3b39670-70bc-49c6-a52b-7e1ddf753ba7
14097,26,blue_collar,SINGLE,high.school,0.0,0.0,1.0,telephone,251,2,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,962",5228,no,14-noviembre-2016,35.897,-121.424,69438,1,2,2012-01-16,9,069f040a-db64-4435-a8cd-f4b5a8ecc6d9
6526,36,management,SINGLE,university.degree,0.0,1.0,0.0,telephone,145,3,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,29-diciembre-2016,26.268,-67.019,136495,0,0,2012-03-15,28,db18b4af-512b-4124-a304-6c2c440d5b0d

In [11]:
meses = {
    'enero':'01', 'febrero':'02', 'marzo':'03', 'abril':'04',
    'mayo':'05', 'junio':'06', 'julio':'07', 'agosto':'08',
    'septiembre':'09', 'octubre':'10', 'noviembre':'11', 'diciembre':'12'
}

for mes_texto, mes_num in meses.items():
    df_u['date'] = df_u['date'].str.replace(mes_texto, mes_num)


for col in ['date', 'dt_customer']:
    df_u[col] = pd.to_datetime(df_u[col], dayfirst=True, errors='coerce')

In [12]:
cols = ['default', 'housing', 'loan']

for col in cols:

   df_u[col + '_str'] = df_u[col].astype(object).replace({0.0: 'No', 1.0: 'Yes'})

TODO EL DATA FRAME

conversion a minusculas,   
"." por "_",  
"," por ".",   e Integer por float

In [13]:
sl.minus(df_u)

In [14]:
sl.puntos(df_u)

In [15]:
sl.comas_float(df_u)

In [16]:
df_u = df_u.rename(columns={'y': 'subscription_prod','date':'date_contact' })

In [17]:
se.eda_preliminar(df_u)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,subscription_prod,date_contact,latitude,longitude,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,default_str,housing_str,loan_str
5520,<NA>,admin,married,university_degree,NaN,0.0,1.0,telephone,61,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no,2019-10-05,48.102,-68.990,100075,0,0,2012-12-07,27,5ef513b2-5688-4a40-acc9-7fb718dc0c98,NaN,no,yes
17968,28,self_employed,married,university_degree,0.0,1.0,0.0,cellular,695,1,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228,no,2015-05-15,29.048,-121.830,148311,2,2,NaT,9,63489489-1595-4597-b9a2-5da2b1c380d1,no,yes,no
11637,43,services,married,high_school,0.0,0.0,0.0,telephone,16,7,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228,no,2017-12-08,47.893,-120.224,36820,0,2,NaT,24,2de1e730-ac0b-4aad-ad35-73a73f2c3d6d,no,no,no
26953,47,management,married,university_degree,0.0,0.0,0.0,cellular,107,2,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195,no,2015-12-26,46.427,-122.509,103963,0,0,NaT,25,11571ad7-c55a-42bc-8c27-a0641210d2f5,no,no,no
7778,32,blue_collar,single,basic_4y,0.0,1.0,1.0,telephone,156,1,999,0,nonexistent,1.4,94.465,-41.8,NaN,5228,no,2017-11-20,48.064,-82.311,171762,1,1,NaT,11,3ffcf79f-623b-4cc8-8dff-0ab40cb62ecc,no,yes,yes

------------------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 43000 filas y 31 columnas
------------------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  Int64
 1   job                42655 non-null  object
 2   marital            42915 non-null  object
 3   education          41193 non-null  object
 4   default            34019 non-null  float64
 5   housing            41974 non-null  float64
 6   loan               41974 non-null  float64
 7   contact            43000 non-null  object
 8   duration           43000 non-null  int64
 9   campaign           43000 non-null  int64
 10  pdays              43000 non-null  int64
 11  previous           43000 non-null  int64
 12  poutcome           43000 non-null  object
 13  emp_var_rate       43000 non-null  float64
 14  cons_price_idx     42529 non-null  float64
 15  cons_conf_idx      43000 non-null  float64
 16  euribor3m          33744 non-null  float64
 17  nr_employed        43000 non-null  int64
 18  subscription_prod  43000 non-null  object
 19  date_contact       42752 non-null  datetime64[ns]
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  income             43000 non-null  int64
 23  kidhome            43000 non-null  int64
 24  teenhome           43000 non-null  int64
 25  dt_customer        16867 non-null  datetime64[ns]
 26  numwebvisitsmonth  43000 non-null  int64
 27  id                 43000 non-null  object
 28  default_str        34019 non-null  object
 29  housing_str        41974 non-null  object
 30  loan_str           41974 non-null  object
dtypes: Int64(1), datetime64[ns](2), float64(9), int64(9), object(10)
memory usage: 10.2+ MB

None

------------------------
NULOS

age                  11.906977
job                   0.802326
marital               0.197674
education             4.202326
default              20.886047
housing               2.386047
loan                  2.386047
contact               0.000000
duration              0.000000
campaign              0.000000
pdays                 0.000000
previous              0.000000
poutcome              0.000000
emp_var_rate          0.000000
cons_price_idx        1.095349
cons_conf_idx         0.000000
euribor3m            21.525581
nr_employed           0.000000
subscription_prod     0.000000
date_contact          0.576744
latitude              0.000000
longitude             0.000000
income                0.000000
kidhome               0.000000
teenhome              0.000000
dt_customer          60.774419
numwebvisitsmonth     0.000000
id                    0.000000
default_str          20.886047
housing_str           2.386047
loan_str              2.386047
dtype: float64

------------------------
DUPLICADOS
0
------------------------
FRECUENCIA CATEGORICAS
JOB
job
admin            10873
blue_collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self_employed     1489
housemaid         1123
unemployed        1063
student            903
Name: count, dtype: int64
------------------------
MARITAL
marital
married     25999
single      12105
divorced     4811
Name: count, dtype: int64
------------------------
EDUCATION
education
university_degree      12722
high_school             9925
basic_9y                6309
professional_course     5477
basic_4y                4356
basic_6y                2386
illiterate                18
Name: count, dtype: int64
------------------------
CONTACT
contact
cellular     27396
telephone    15604
Name: count, dtype: int64
------------------------
POUTCOME
poutcome
nonexistent    37103
failure         4461
success         1436
Name: count, dtype: int64
------------------------
SUBSCRIPTION_PROD
subscription_prod
no     38156
yes     4844
Name: count, dtype: int64
------------------------
ID
id
089b39d8-e4d0-461b-87d4-814d71e0e079    1
e9d37224-cb6f-4942-98d7-46672963d097    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
eca60b76-70b6-4077-80ba-bc52e8ebb0eb    1
                                       ..
4eed05de-2a98-4227-b488-32122009b638    1
0f0aca88-4088-4fe2-905f-44fb675d9493    1
cadadd4b-7ee5-4019-b13a-ca01bb67ca5b    1
5f432048-d515-4bb5-9c94-62db451f88d4    1
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
Name: count, Length: 43000, dtype: int64
------------------------
DEFAULT_STR
default_str
no     34016
yes        3
Name: count, dtype: int64
------------------------
HOUSING_STR
housing_str
yes    22498
no     19476
Name: count, dtype: int64
------------------------
LOAN_STR
loan_str
no     35442
yes     6532
Name: count, dtype: int64
------------------------
------------------------
ESTADISTICOS NUMERICAS

,count,mean,min,25%,50%,75%,max,std
age,37880.0,39.977112,17.0,32.0,38.0,47.0,98.0,10.437957
default,34019.0,0.000088,0.0,0.0,0.0,0.0,1.0,0.00939
housing,41974.0,0.535998,0.0,0.0,1.0,1.0,1.0,0.498708
loan,41974.0,0.15562,0.0,0.0,0.0,0.0,1.0,0.362499
duration,43000.0,257.739279,0.0,102.0,179.0,319.0,4918.0,258.666033
campaign,43000.0,2.567233,1.0,1.0,2.0,3.0,56.0,2.772294
pdays,43000.0,962.330953,0.0,999.0,999.0,999.0,999.0,187.260394
previous,43000.0,0.174023,0.0,0.0,0.0,0.0,7.0,0.497366
emp_var_rate,43000.0,0.077128,-3.4,-1.8,1.1,1.4,1.4,1.573898
cons_price_idx,42529.0,93.574219,92.201,93.075,93.749,93.994,94.767,0.579548
cons_conf_idx,43000.0,-40.509049,-50.8,-42.7,-41.8,-36.4,-26.9,4.637186
euribor3m,33744.0,3.616521,0.634,1.344,4.857,4.961,5.045,1.737117
nr_employed,43000.0,5166.66586,4963.0,5099.0,5191.0,5228.0,5228.0,72.488304
date_contact,42752,2017-07-01 19:55:11.676646656,2015-01-01 00:00:00,2016-04-01 00:00:00,2017-07-04 00:00:00,2018-10-01 06:00:00,2019-12-31 00:00:00,NaN
latitude,43000.0,36.856697,24.396,30.61475,36.761,43.11325,49.384,7.225948
longitude,43000.0,-95.939067,-124.997,-110.49425,-95.8995,-81.42775,-66.937,16.752282
income,43000.0,93241.20007,5841.0,49610.0,93050.5,136744.5,180802.0,50498.316182
kidhome,43000.0,1.004791,0.0,0.0,1.0,2.0,2.0,0.815913
teenhome,43000.0,0.998605,0.0,0.0,1.0,2.0,2.0,0.815983
dt_customer,16867,2013-05-05 06:21:21.887709952,2012-01-01 00:00:00,2012-07-07 00:00:00,2013-03-01 00:00:00,2014-03-11 00:00:00,2014-12-12 00:00:00,NaN
numwebvisitsmonth,43000.0,16.589698,1.0,9.0,17.0,25.0,32.0,9.239205

In [18]:
df_u.to_csv('../Datos/df_data_limpios.csv', index=False)